name: Deploy Helm Chart to AWS EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#All keys and credentials will be stored in GitHub secrets
env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: weather-app-cluster
  HELM_CHART_NAME: weather-app 
  NAMESPACE: default 
  DOCKER_IMAGE: chinedu101/weatherapp 
  API_KEY: ${{ secrets.SECURE_WEATHER_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Set up kubectl
      - name: install kubectl
        run:  |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/ 

      # Step 4: Update kubeconfig to use the EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      # Step 5: Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 6: Deploy Helm chart to EKS cluster
      - name: Deploy Helm chart
        run: |
          helm upgrade --install ${{ env.HELM_CHART_NAME }} ./weather-app \
            --namespace ${{ env.NAMESPACE }} \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set env.SECURE_WEATHER_API_KEY=${{ secrets.SECURE_WEATHER_API_KEY }} \
            --set image.tag=latest \
           

     


